# Generated by Django 5.0.4 on 2024-05-01 13:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_credentials', models.ImageField(upload_to='student/credentials')),
                ('financial_need', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_raised', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('campaign_message', models.TextField()),
                ('campaign_status', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Ongoing', max_length=15)),
                ('payment_deadline', models.DateField()),
                ('is_approve', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_student', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Campaign',
                'verbose_name_plural': 'Student Campaigns',
            },
        ),
    ]
