# Generated by Django 5.0.4 on 2024-05-01 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_studentcampaign_student_university'),
        ('university', '0003_university_is_approve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='university_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_university_id', to='university.university'),
        ),
    ]
