# Generated by Django 5.0.4 on 2024-05-01 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_university_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='university_id',
            new_name='university',
        ),
    ]
