# Generated by Django 5.0.4 on 2024-05-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='university',
            name='account_number',
            field=models.IntegerField(),
        ),
    ]
