# Generated by Django 5.0.4 on 2024-05-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_university_slug_alter_university_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='is_approve',
            field=models.BooleanField(default=False),
        ),
    ]
